version: '3.7'
services:
  web:
    build: .
    ports:
      - '5400:5400'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql:/var/lib/mysql
