version: '3.7'
networks:
  default:
    external:
      name: pis-septemberlabs
services:
  api:
    build:
      context: ${PARENT_PWD}/capacitacion-docker
    container_name: pis-septemberlabs_api
    command: npm run dev
    ports:
      - '5000:5000'
    volumes:
      - ${PARENT_PWD}/capacitacion-docker/src:/app/capacitacion-docker/src
      - ${PARENT_PWD}/capacitacion-docker/.env:/app/capacitacion-docker/.env
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: pis-septemberlabs_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql:/var/lib/mysql
